### ISSUE TITLE
JSON encoding body is painful

### ISSUE THREAD

**Issue by quittle** [stechstudio/php-lambda#1]
Hi, I've been trying to consume your Lambda layer for a Lambda Proxy integration behind API Gateway. I am trying to return non-JSON data (HTML) but [the body gets `json_encode`d](https://github.com/stechstudio/php-lambda/blob/master/helpers/bootstrap#L195-L198) in your bootstrap. This would also play havoc if the lambda was trying to return arbitrary data and not JSON. Could you expose some type of flag to customize the encoding of the response or leave it as is?

It took a bit to understand how to integrate without a readme, but once I got figured it out, the integration makes a lot of sense. Just the encoding issue is blocking me from using this for my project.

**Comment by bubba-h57** [comment]
Could you give me an example of what your lambda job is returning? And what you are seeing in the browser?

I would expect the html to be the body of the response object, which would get transformed into JSON and sent back to API Gateway (along with appropriate POST fields and HEADERS). API Gateway (acting as a lambda proxy) should unravel the JSON properly and the browser should only get the HTML.

It just struck me, are you setting up API Gateway using the Lambda Proxy Integration?

![2019-07-16_16-40-58](https://user-images.githubusercontent.com/603630/61328237-94ab0d00-a7e8-11e9-8af9-8830b2849a51.png)

**Comment by bubba-h57** [comment]
Also ... are you aware of [bref](https://github.com/brefphp/bref) ... if you are looking for a rock solid, end user-friendly PHP layer, they may be more of a fit for you? We contribute to the project, and their build process is close to identical to this one. However, they have a much larger community for support and .... well ... actual documentation. :-)

**Comment by quittle** [comment]
I'm actually trying to migrate a [LAMP stack](https://en.wikipedia.org/wiki/LAMP_(software_bundle)) application to Lambda to save costs. The routes provide a variety of responses with different content types. Most return `text/html`, some return `application/json`, some return `text/plain` and one returns `image/jpeg`. I plan on trying to it mostly running on Lambda and swap out the database from MySQL to DynamoDB. The problem I faced with this bootstrap was that I would try to return something like the following from my handler.

```php
array(
    'body' => '<body>text</body>',
    'headers' => array(
        'Content-Type' => 'text/html',
        'x-custom-header' => 'custom-value'
    )
)
```

Because of the body `json_encode`, however, the lambda would return a response like

```json
{
    "body": "\"<body>text</body>\"",
    "headers": {
        "Content-Type": "text/html",
        "x-custom-header": "custom-value"
    }
}
```

I could then see my header being properly returned by API Gateway, but the content was always wrapped in `"`, which broke `<!DOCTYPE>` detection as it wasn't on the page.

---

**bref** looks very promising. I'll check that out and see if I can get it to work for me

**Comment by bubba-h57** [comment]
Ya, bref is intended to specifically address your use case.
