### ISSUE TITLE
Support for autoloading / spl_autoload_register

### ISSUE THREAD

**Issue by jstrese** [stechstudio/php-lambda#2]
It looks like pthreads isn't passing autoloaded resources to new threads, and calling the autoloader from a new thread also doesn't seem to have any impact.

Have you found a workaround to get spl_autoload_register to function as "normal" using your threaded design in this project?

**Comment by bubba-h57** [comment]
I have not. And given krakjoe/pthreads#929  I sorta stopped chasing it. I didn't see a use for something that will defunct in no time at all.

**Comment by jstrese** [comment]
Thanks for the link @bubba-h57. I checked out Bref and their runtime seems to work for my purpose :) so thanks for mentioning Bref in the other issue on this project. 

Good luck with your future development here! The code was pleasant to read, very well structured and written.
